### ISSUE TITLE
ERROR: Parser error: syntax error in file IKEA_Samla_Inserts.scad, line 7  Execution aborted

### ISSUE THREAD

**Issue by Plaethe** [Alex9779/IKEA-Samla-Inserts#10]
Downloaded the latest portable from https://openscad.org/downloads and when I open the IKEA_Samla_Inserts.scad, then the following error message is shown: 

ERROR: Parser error: syntax error in file IKEA_Samla_Inserts.scad, line 7 - Execution aborted

Line 7 is "!DOCTYPE html" in: 

```
<!DOCTYPE html>
<html lang="en" data-color-mode="dark" data-light-theme="light" data-dark-theme="dark_dimmed">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
  <link rel="preconnect" href="https://github.githubassets.com" crossorigin>
  <link rel="preconnect" href="https://avatars.githubusercontent.com">
```

I am new to openscad. I do really get the issue, even after checking their documentation, or maybe I misunderstood the tutorial. Can somebody tell me whats wrong?

**Comment by Alex9779** [comment]
Strange, how did you download the file? Looks like you saved the Github webpage...
The real scad script is just text and does not look like what you posted.
Go back to the "Code" tab of the repository then hit the green button in the upper right corner labeled "Code" and choose "Download ZIP", unzip that file and try again with the scad file you have then...

**Comment by Plaethe** [comment]
Yep, downloading as zip worked well and expected! Thx!
