### ISSUE TITLE
Ability to print two half 5L inserts

### ISSUE THREAD

**Issue by jhaals** [Alex9779/IKEA-Samla-Inserts#12]
First of all this is such a great project making the IKEA boxes better.
I own a Prusa Mini and the 5L box in itself is too big to fit the print bed. Do you think it would be possible to create a split design with a left/wright half that support each other?

<img width="878" alt="Screenshot 2022-05-12 at 20 21 38" src="https://user-images.githubusercontent.com/68980/168143204-b2e1332e-ca6c-4952-8569-aa3b3b20f87a.png">

**Comment by Alex9779** [comment]
There is already, look at the "Part" variable, you can print halves either by row or column or a quater...

**Comment by jhaals** [comment]
Thanks I'll take a look 👍

**Comment by Alex9779** [comment]
Do you need any further assistance and did you find the option?
If so it would be nice if you close this issue.
