### ISSUE TITLE
Change Wall height

### ISSUE THREAD

**Issue by maxbec** [Alex9779/IKEA-Samla-Inserts#13]
Would be great to have the option to change the wall height in smaller steps. Not just layers.

So for example 80% of total Box height.

**Comment by Alex9779** [comment]
What would you need that for? Please describe your use case...
One insert 80% of the box or 2 insert max at 80%?

Actually you can do that, 80% is 4/5 so you set it to 5 layers, then use the combine layers function and set active to one and combine to three you get one insert of 80% height, for two inserts set combine to 1 for active layer 1 and 3...

I admit a direct setting of the height would be easier but the whole thing is layer based so I am not sure how easy this could be implemented and if that is so much useful...

**Comment by maxbec** [comment]
Ah perfect! Thank you very much. I didnt know the combine function! Great work man!
