### ISSUE TITLE
Grid only

### ISSUE THREAD

**Issue by maxbec** [Alex9779/IKEA-Samla-Inserts#14]
Good morning,

is there any chance to just print the grid without the outer walls?
Would be great to save filament.

Thank you.

**Comment by Alex9779** [comment]
Unfortunately not, I see what I can do, should not be so hard...

**Comment by maxbec** [comment]
![Screenshot 2022-09-26 at 09 34 48](https://user-images.githubusercontent.com/8254514/192219063-7fd67e9c-03b3-4762-a204-0e2f5641ddfa.png)
I just commented out these two sections. Maybe it works.

**Comment by Alex9779** [comment]
Well yeah, I added an option for the customizer in https://github.com/Alex9779/IKEA-Samla-Inserts/tree/14-grid-only
It is in the advanced section, if thats ok for you I will merge to master...

**Comment by maxbec** [comment]
Great! Thank you!
