### ISSUE TITLE
Parallelize file generation

### ISSUE THREAD

**Issue by Stefan-Hanke** [Alex9779/IKEA-Samla-Inserts#15]
Hey, just found out about these Inlays like last week and been printing a whole bunch of them. 👍 
This is not an actual _issue_.

Using OpenSCAD UI is tedious for model generation, and I only saw later that you have scripts here. I just want to showcase another approach. I'm now using **[fd](https://github.com/sharkdp/fd)** to find the parameter json files, and run it using [command execution](https://github.com/sharkdp/fd#command-execution). This has the benefit that it runs in parallel. Yeah prints will take way longer, however I'm impatient ;)

```shelll
fd -e json -x "/c/Program Files/OpenSCAD/openscad.exe" ../IKEA_Samla_Inserts.scad -p {} -o {.}.3mf
```

I do parameter file generation manual, create a folder, copy a sample JSON in there, and modify them. Maybe a small script to generate the JSONs given a few params could be of help here also.

**Comment by Alex9779** [comment]
Nice idea, so you use the JSON files of the customizer...
Parallel sounds cool but considering my experience generating models all my PCs are topped when doing just one.
But I see that you can control that and restrict to just one thread also.

I will take this into account next time I am going to need to generate multiple layers and maybe rework the demo scripts with some pre-created JSON files for the customizer.

Though an external dependency of a non-native program is not so nice and maybe just an option for those who want more like you.

Many thanks for the suggestion, feel free to create something general/optional and create a PR.
For now I think we can close...
