### ISSUE TITLE
cutout height

### ISSUE THREAD

**Issue by rdmueller** [Alex9779/IKEA-Samla-Inserts#8]
it would be great if the top layer would sit on top of the cutouts.
this would allow me to only use one inset on top of a box with lots of space underneath it.

Example: 5L box with 3 layers, showing top layer:

![image](https://user-images.githubusercontent.com/1856308/119409971-5fc34780-bce8-11eb-8899-fe5a1923c381.png)

**Comment by rdmueller** [comment]
just noticed that we might make this optional in order to have a version which is easiert to print without supports

**Comment by Alex9779** [comment]
> it would be great if the top layer would sit on top of the cutouts.

Yes, for some applications this might be desirable just like the inserts you can buy from IKEA but without a handle and with a custom grid.

> just noticed that we might make this optional in order to have a version which is easiert to print without supports

That is exactly what I wanted to answer. I printed full sets only and I don't want to deal with supports.
For simple selection this option should also directly print the top layer of the desired layer count. Or maybe not and it will be an option just when I implement #6 for single layer printing.

**Comment by rdmueller** [comment]
I think I will try to modify my changes in such a way that there will be an option which is disabled by default. Would that be ok for you to accept the PR?

**Comment by Alex9779** [comment]
Yeah please make an option, I consider this a special use case as already described...

**Comment by rdmueller** [comment]
ok, the "correct" cutouts are now optional. Defaults to full cutouts for easier printing

**Comment by rdmueller** [comment]
fits quite nice!

![WIN_20210525_16_53_39_Pro](https://user-images.githubusercontent.com/1856308/119519778-00ae1300-bd7a-11eb-8c4c-7f87ed536744.jpg)

**Comment by rdmueller** [comment]
btw: I used tree-style supports for the cutouts and it worked like a charm.
